spring:
    application:
        name: kubernetes
    datasource:
        url: jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/sample
        username: ${DB_USER_NAME:root}
        password: ${DB_PASSWORD:dev4pointchain}
        driver-class-name: com.mysql.cj.jdbc.Driver
        hikari:
            minimum-idle: 5
            maximum-pool-size: 20
            idle-timeout: 30000
            pool-name: HikariPool-1
    jpa:
        hibernate:
            ddl-auto: update
        properties:
            hibernate:
                dialect: org.hibernate.dialect.MySQL8Dialect

server:
    port: ${PORT:9090}

management:
    endpoints:
        web:
            exposure:
                include:
                    - health
                    - info
    endpoint:
        health:
            show-details: always
